---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: _manage
  label: KB manage
  create: all
  match: "**/*"
  templates:
  - knowledge-base
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _data
  label: Data
  create: all
  match: "*.yml"
  new_doc_ext: yml
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
